### ISSUE TITLE
avoid string allocation for each request

### ISSUE THREAD

**Issue by vtolstov** [storj/drpc#19]
if you change generator and generate for each method const variable name like

```
const (
  accountAccontServiceCreate = "/account.AccountService/Create"
)

func (c *drpcAccountServiceClient) Create(ctx context.Context, in *AccountCreateReq) (*Account, error) {
        out := new(Account)
        err := c.cc.Invoke(ctx, accountAccontServiceCreate, drpcEncoding_File_account_proto{}, in, out)
        if err != nil {
                return nil, err
        }
        return out, nil
}
```

we completely can avoid new string allocation for each request and minimize garbage.
what you think ?

**Comment by vtolstov** [comment]
also this can be used for server generated code too in switch cases

**Comment by zeebo** [comment]
Unfortunately, using a `const` doesn't fix the problem. The allocation happens in the `*drpcconn.Conn` package where it converts the `string` to a `[]byte` here: https://github.com/storj/drpc/blob/main/drpcconn/conn.go#L85. The reason why that allocates is because the compiler can't prove it doesn't escape. The reason it can't prove it doesn't escape is because the slice is eventually passed into a `drpcwire.SplitN` call. That function does iteration with a callback function (https://github.com/storj/drpc/blob/main/drpcwire/split.go#L10) which is virtual dispatch. It's possible for a provided function to mutate the given byte slice, so it is forced to copy (and the compiler does not inline `SplitN` so it can't tell that none of the provided callbacks do this).

Fortunately, I looked into all this last friday and created a change to remove the allocation: https://review.dev.storj.io/c/storj/drpc/+/5062

So this should be fixed, soon :smile:

**Comment by vtolstov** [comment]
nice to hear, if i have own generator to my framework can you say me - how to detect escaping?

**Comment by vtolstov** [comment]
i'm read che changeset, but as i understand this fixes additional allocation, but allocation for method name (string) happens always (but yes it garbage collected), but i don't understand why to avoid allocations in generated code too.

**Comment by egonelbre** [comment]
@vtolstov using a string literal does not allocate. Go internally has a read-only section in the binary for those strings. String allocation happens when you create one dynamically (e.g. add two unknown strings together), or when you convert a byte slice (which has other references) to a string.

You can use https://github.com/loov/view-annotated-file to view escaping to the heap -- which usually indicates allocation. Alternatively, benchmark.

**Comment by vtolstov** [comment]
nice, thank you

**Comment by zeebo** [comment]
Released!
